import { ISOFieldDefinition } from '../../src/types/payment.js';

export const ISO_FIELD_DEFINITIONS: Record<number, ISOFieldDefinition> = {
  1: { fieldNumber: 1, name: 'Secondary Bitmap', type: 'BINARY', maxLength: 8, description: 'Bitmap indicating presence of fields 65-128' },
  2: { fieldNumber: 2, name: 'Primary Account Number (PAN)', type: 'LLVAR_NUMERIC', maxLength: 19, description: 'Cardholder PAN or virtual token' },
  3: { fieldNumber: 3, name: 'Processing Code', type: 'NUMERIC', maxLength: 6, description: 'Transaction type code (e.g. 000000 Purchase, 200000 Refund, 010000 Cash)' },
  4: { fieldNumber: 4, name: 'Amount, Transaction', type: 'NUMERIC', maxLength: 12, description: 'Transaction amount in minor currency units (paise for INR)' },
  7: { fieldNumber: 7, name: 'Transmission Date & Time', type: 'NUMERIC', maxLength: 10, description: 'MMDDhhmmss in UTC' },
  11: { fieldNumber: 11, name: 'System Trace Audit Number (STAN)', type: 'NUMERIC', maxLength: 6, description: 'Unique trace identifier assigned by terminal/acquirer' },
  12: { fieldNumber: 12, name: 'Time, Local Transaction', type: 'NUMERIC', maxLength: 6, description: 'hhmmss in local terminal time' },
  13: { fieldNumber: 13, name: 'Date, Local Transaction', type: 'NUMERIC', maxLength: 4, description: 'MMDD in local terminal date' },
  14: { fieldNumber: 14, name: 'Date, Expiration', type: 'NUMERIC', maxLength: 4, description: 'YYMM card expiration' },
  18: { fieldNumber: 18, name: 'Merchant Category Code (MCC)', type: 'NUMERIC', maxLength: 4, description: 'Merchant industry classification code' },
  22: { fieldNumber: 22, name: 'Point of Service Entry Mode', type: 'NUMERIC', maxLength: 3, description: '051=EMV Chip, 071=Contactless NFC, 021=Magstripe, 012=E-com' },
  23: { fieldNumber: 23, name: 'Card Sequence Number', type: 'NUMERIC', maxLength: 3, description: 'EMV chip sequence number' },
  25: { fieldNumber: 25, name: 'Point of Service Condition Code', type: 'NUMERIC', maxLength: 2, description: '00=Normal, 08=Mail/Phone, 59=E-commerce' },
  32: { fieldNumber: 32, name: 'Acquiring Institution ID Code', type: 'LLVAR_NUMERIC', maxLength: 11, description: 'BIN / Bank ID of acquiring entity' },
  35: { fieldNumber: 35, name: 'Track 2 Data', type: 'LLVAR_ALPHANUMERIC', maxLength: 37, description: 'Card magnetic stripe or chip equivalent track 2' },
  37: { fieldNumber: 37, name: 'Retrieval Reference Number (RRN)', type: 'ALPHANUMERIC', maxLength: 12, description: 'Globally unique 12-digit payment reference' },
  38: { fieldNumber: 38, name: 'Authorization Identification Response', type: 'ALPHANUMERIC', maxLength: 6, description: 'Issuer auth approval code' },
  39: { fieldNumber: 39, name: 'Response Code', type: 'ALPHANUMERIC', maxLength: 2, description: '00=Approved, 51=Insufficient Funds, 55=Incorrect PIN, etc.' },
  41: { fieldNumber: 41, name: 'Card Acceptor Terminal ID (TID)', type: 'ALPHANUMERIC', maxLength: 8, description: 'Terminal identifier at merchant' },
  42: { fieldNumber: 42, name: 'Card Acceptor ID Code (MID)', type: 'ALPHANUMERIC', maxLength: 15, description: 'Merchant identification code' },
  43: { fieldNumber: 43, name: 'Card Acceptor Name/Location', type: 'ALPHANUMERIC', maxLength: 40, description: 'Merchant display name, city, and country code' },
  48: { fieldNumber: 48, name: 'Private Additional Data', type: 'LLLVAR_ALPHANUMERIC', maxLength: 999, description: 'UPI VPA, sub-merchant data, or dynamic parameters' },
  49: { fieldNumber: 49, name: 'Currency Code, Transaction', type: 'NUMERIC', maxLength: 3, description: 'ISO 4217 numeric (356 = INR)' },
  52: { fieldNumber: 52, name: 'Personal ID Number (PIN) Data', type: 'BINARY', maxLength: 8, description: 'Encrypted ISO 9564 PIN block (16 hex chars)' },
  53: { fieldNumber: 53, name: 'Security Related Control Information', type: 'NUMERIC', maxLength: 16, description: 'Key management and security scheme indicators' },
  54: { fieldNumber: 54, name: 'Additional Amounts', type: 'LLLVAR_ALPHANUMERIC', maxLength: 120, description: 'Surcharge, cash-back or tip amounts' },
  55: { fieldNumber: 55, name: 'Integrated Circuit Card (ICC) System Related Data', type: 'LLLVAR_BINARY', maxLength: 999, description: 'EMV Tag 55 TLV payload containing ARQC, ATC, IAD, TVR, AIP' },
  60: { fieldNumber: 60, name: 'Private Use (Terminal Info)', type: 'LLLVAR_ALPHANUMERIC', maxLength: 100, description: 'Terminal capabilities, batch number, OS version' },
  62: { fieldNumber: 62, name: 'Invoice / Ticket Reference Number', type: 'LLLVAR_ALPHANUMERIC', maxLength: 100, description: 'Order ID or custom invoice reference' },
  70: { fieldNumber: 70, name: 'Network Management Information Code', type: 'NUMERIC', maxLength: 3, description: '001=Logon, 002=Logoff, 301=Echo test' },
  90: { fieldNumber: 90, name: 'Original Data Elements (Reversal Reference)', type: 'NUMERIC', maxLength: 42, description: 'Original MTI + STAN + Transmission Time + Acquirer ID' },
  102: { fieldNumber: 102, name: 'Account Identification 1', type: 'LLVAR_ALPHANUMERIC', maxLength: 28, description: 'Debited account number or VPA' },
  103: { fieldNumber: 103, name: 'Account Identification 2', type: 'LLVAR_ALPHANUMERIC', maxLength: 28, description: 'Credited merchant account or beneficiary VPA' },
  123: { fieldNumber: 123, name: 'POS Delivery Channel Data', type: 'LLLVAR_ALPHANUMERIC', maxLength: 150, description: 'Routing indicators and network switch trace flags' }
};

export const RESPONSE_CODES: Record<string, { description: string; category: 'SUCCESS' | 'USER_ERROR' | 'SYSTEM_ERROR' | 'FRAUD' }> = {
  '00': { description: 'Approved / Successful Transaction', category: 'SUCCESS' },
  '01': { description: 'Refer to Card Issuer (Call Bank)', category: 'USER_ERROR' },
  '05': { description: 'Do Not Honor / General Decline', category: 'USER_ERROR' },
  '12': { description: 'Invalid Transaction Type', category: 'SYSTEM_ERROR' },
  '13': { description: 'Invalid Amount Value', category: 'USER_ERROR' },
  '14': { description: 'Invalid Card Number (No Such Number)', category: 'USER_ERROR' },
  '30': { description: 'Format Error in ISO 8583 Packet', category: 'SYSTEM_ERROR' },
  '41': { description: 'Lost Card (Pick Up Card)', category: 'FRAUD' },
  '43': { description: 'Stolen Card (Pick Up Card)', category: 'FRAUD' },
  '51': { description: 'Insufficient Funds / Credit Limit Exceeded', category: 'USER_ERROR' },
  '54': { description: 'Expired Card', category: 'USER_ERROR' },
  '55': { description: 'Incorrect PIN Entered', category: 'USER_ERROR' },
  '57': { description: 'Transaction Not Permitted to Cardholder', category: 'USER_ERROR' },
  '58': { description: 'Transaction Not Permitted to Merchant Terminal', category: 'SYSTEM_ERROR' },
  '59': { description: 'Suspected Fraud / Risk Engine Block', category: 'FRAUD' },
  '61': { description: 'Exceeds Transaction Withdrawal / Velocity Limit', category: 'FRAUD' },
  '65': { description: 'Exceeds Daily Activity Count Limit', category: 'USER_ERROR' },
  '75': { description: 'Allowable PIN Tries Exceeded', category: 'FRAUD' },
  '91': { description: 'Issuer Switch or Host Inoperative / Timeout', category: 'SYSTEM_ERROR' },
  '92': { description: 'Financial Institution Cannot Be Routed', category: 'SYSTEM_ERROR' },
  '94': { description: 'Duplicate Transmission / STAN Conflict', category: 'SYSTEM_ERROR' },
  '96': { description: 'System Malfunction / HSM Cryptogram Failure', category: 'SYSTEM_ERROR' }
};
